---
title: "`r params$title`"
date: "`r format(params$time, '%Y-%m-%d %H:%M:%S')`"
output: 
  powerpoint_presentation
params:
  title: "Default Title"
  time: !r Sys.time()
  data1: NULL
  data2: NULL
  result: NULL
  plot_time1: NULL
  plot_time2: NULL
  scatter_max: NULL
  scatter_global: NULL
  align_max: NULL
  align_global: NULL
  eva_plot: NULL
---

## Data Preview - Dataset 1

```{r, echo=FALSE}
head(params$data1, 5)
```

## Data Preview - Dataset 2

```{r, echo=FALSE}
head(params$data2, 5)
```

---

## File 1 Time Plot

```{r, echo=FALSE}
params$plot_time1
```

## File 2 Time Plot

```{r, echo=FALSE}
params$plot_time2
```

---

## Correlation Summary

```{r, echo=FALSE}
result <- params$result
result
```

---

## Max Correlation

```{r}
lagci::extract_max_cor(result)
```

## Global Correlation

```{r}
lagci::extract_global_cor(result)
```

## Shift Time

```{r}
lagci::extract_shift_time(result)
```

## Evaluation Score

```{r}
lagci::evaluate_lagged_cor(result, plot = FALSE)$score
```

---

## Evaluated Lagged Correlation Plot

```{r, echo=FALSE}
params$eva_plot
```

## Max Alignment Plot

```{r, echo=FALSE}
params$align_max
```

## Max Scatter Plot

```{r, echo=FALSE}
params$scatter_max
```

## Global Alignment Plot

```{r, echo=FALSE}
params$align_global
```

## Global Scatter Plot

```{r, echo=FALSE}
params$scatter_global
```

---

## Session Info

```{r}
sessionInfo()
```