---
title: ""
output: 
  html_document:
    toc: false
    toc_float:
      collapsed: false
      smooth_scroll: true
    number_sections: false
date: "2025-08-04"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Introduction

`laggedcor` is an R package designed for calculating lagged correlations between two time-series datasets, with a particular focus on wearable and omics data analysis. Developed by Dr. Xiaotao Shen, this tool is available on GitHub at [https://github.com/jaspershen-lab/laggedcor](https://github.com/jaspershen-lab/laggedcor).

`laggedcor` is part of the larger tidywearable ecosystem, which provides a comprehensive suite of tools for wearable data analysis. This integration ensures compatibility and workflow continuity for researchers working with multiple types of temporal health data.

The package includes demonstration datasets that illustrate typical use cases: `heart_data` containing heart rate measurements and `step_data` containing step count measurements. These datasets exemplify the type of wearable device data that researchers commonly need to analyze for temporal relationships.

# Contacts

If you have any questions about laggedcor, please contact Dr. Xiaotao Shen.


<i class="fa fa-envelope"></i> shenxt@stanford.edu

<i class="fa-brands fa-square-x-twitter"></i> [X](https://x.com/xiaotaoshen1990)

<i class="fa fa-map-marker-alt"></i> [Experimental Medicine Building (EMB), 59 Nanyang Dr, Singapore 636921](https://www.google.com/maps/place/Experimental+Medicine+Building+(EMB)/@1.3446589,103.6759014,17z/data=!3m2!4b1!5s0x31da0fa062fb6e8b:0x7a7422f5cbf93df8!4m6!3m5!1s0x31da0f74c11959dd:0x1a2e60ac1237b269!8m2!3d1.3446535!4d103.6784763!16s%2Fg%2F11bwpz7vzw?entry=ttu&g_ep=EgoyMDI1MDczMC4wIKXMDSoASAFQAw%3D%3D)
